use_frameworks!

target 'swiftly-battle-net_Example' do
  pod 'swiftly-battle-net', :path => '../'

  target 'swiftly-battle-net_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
