language: objective-c
osx_image: xcode7.3
notifications:
  email: false
script:
- set -o pipefail
- xcodebuild test -workspace Example/swiftly-battle-net.xcworkspace -scheme swiftly-battle-net-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
